In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
df = pd.read_csv("../data/processed/HC_application_train_cleaned.csv")

In [3]:
print("Shape:", df.shape)

Shape: (307511, 115)

In [4]:
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LANDAREA_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LANDAREA_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LANDAREA_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,AGE,YEARS_EMPLOYED,INCOME_PER_FAMILY_MEMBER,CREDIT_INCOME_RATIO,ANNUITY_INCOME_RATIO,GOODS_CREDIT_RATIO,CREDIT_TERM,CREDIT_PER_FAMILY_MEMBER,EXT_SOURCE_AVG
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637.0,-3648.0,-2120,9.0,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.00,0.0690,0.0833,0.0369,0.0190,0.0000,0.0252,0.0383,0.9722,0.0000,0.0690,0.0833,0.0377,0.0198,0.0000,0.0250,0.0369,0.9722,0.00,0.0690,0.0833,0.0375,0.0193,0.0000,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,25.9,1.7,202500.0,2.01,0.12,0.86,16.5,406597.50,0.161787
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188.0,-1186.0,-291,9.0,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,0.535276,0.0959,0.0529,0.9851,0.08,0.0345,0.2917,0.0130,0.0549,0.0098,0.0924,0.0538,0.9851,0.0806,0.0345,0.2917,0.0128,0.0554,0.0000,0.0968,0.0529,0.9851,0.08,0.0345,0.2917,0.0132,0.0558,0.0100,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,45.9,3.3,135000.0,4.79,0.13,0.87,36.2,646751.25,0.489596
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225.0,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,0.505998,0.555912,0.729567,0.0876,0.0763,0.9816,0.00,0.1379,0.1667,0.0481,0.0745,0.0036,0.0840,0.0746,0.9816,0.0000,0.1379,0.1667,0.0458,0.0731,0.0011,0.0864,0.0758,0.9816,0.00,0.1379,0.1667,0.0487,0.0749,0.0031,NaN,0.0688,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,52.2,0.6,67500.0,2.00,0.10,1.00,20.0,135000.00,0.597159
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-19005,-3039.0,-9833.0,-2437,9.0,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,0.505998,0.650442,0.535276,0.0876,0.0763,0.9816,0.00,0.1379,0.1667,0.0481,0.0745,0.0036,0.0840,0.0746,0.9816,0.0000,0.1379,0.1667,0.0458,0.0731,0.0011,0.0864,0.0758,0.9816,0.00,0.1379,0.1667,0.0487,0.0749,0.0031,NaN,0.0688,NaN,NaN,2.0,0.0,2.0,0.0,-617.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,52.1,8.3,67500.0,2.32,0.22,0.95,10.5,156341.25,0.563905
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-19932,-3038.0,-4311.0,-3458,9.0,1,1,0,1,0,0,Core staff,1.0,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,0.505998,0.322738,0.535276,0.0876,0.0763,0.9816,0.00,0.1379,0.1667,0.0481,0.0745,0.0036,0.0840,0.0746,0.9816,0.0000,0.1379,0.1667,0.0458,0.0731,0.0011,0.0864,0.0758,0.9816,0.00,0.1379,0.1667,0.0487,0.0749,0.0031,NaN,0.0688,NaN,NaN,0.0,0.0,0.0,0.0,-1106.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,54.6,8.3,121500.0,4.22,0.18,1.00,23.5,513000.00,0.454671

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 115 entries, SK_ID_CURR to EXT_SOURCE_AVG
dtypes: float64(60), int64(40), object(15)
memory usage: 269.8+ MB

In [7]:
missing = (
    df.isnull()
      .sum()
      .sort_values(ascending=False)
)

missing = missing[missing > 0]

missing.head(20)

WALLSMATERIAL_MODE     156341
HOUSETYPE_MODE         154297
EMERGENCYSTATE_MODE    145755
OCCUPATION_TYPE         96391
YEARS_EMPLOYED          55374
DAYS_EMPLOYED           55374
NAME_TYPE_SUITE          1292
dtype: int64

In [8]:
feature_df = df.copy()

In [9]:
binary_cols = [
    "CODE_GENDER",
    "FLAG_OWN_CAR",
    "FLAG_OWN_REALTY",
    "EMERGENCYSTATE_MODE"
]

feature_df[binary_cols].head()

  CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY EMERGENCYSTATE_MODE
0           M            N               Y                  No
1           F            N               N                  No
2           M            Y               Y                 NaN
3           F            N               Y                 NaN
4           M            N               Y                 NaN

In [10]:
feature_df["CODE_GENDER"] = feature_df["CODE_GENDER"].map({
    "M": 1,
    "F": 0
})

In [11]:
feature_df["FLAG_OWN_CAR"] = feature_df["FLAG_OWN_CAR"].map({
    "Y": 1,
    "N": 0
})

In [12]:
feature_df["FLAG_OWN_REALTY"] = feature_df["FLAG_OWN_REALTY"].map({
    "Y": 1,
    "N": 0
})

In [13]:
feature_df["EMERGENCYSTATE_MODE"] = feature_df["EMERGENCYSTATE_MODE"].map({
    "Yes": 1,
    "No": 0
})

In [14]:
feature_df[binary_cols].head()

   CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  EMERGENCYSTATE_MODE
0          1.0             0                1                  0.0
1          0.0             0                0                  0.0
2          1.0             1                1                  NaN
3          0.0             0                1                  NaN
4          1.0             0                1                  NaN

In [15]:
feature_df.select_dtypes(include="object").columns.tolist()

['NAME_CONTRACT_TYPE',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'OCCUPATION_TYPE',
 'WEEKDAY_APPR_PROCESS_START',
 'ORGANIZATION_TYPE',
 'HOUSETYPE_MODE',
 'WALLSMATERIAL_MODE']

In [16]:
cat_cols = feature_df.select_dtypes(include="object").columns.tolist()

print(f"Number of categorical columns: {len(cat_cols)}")
print(cat_cols)

Number of categorical columns: 11
['NAME_CONTRACT_TYPE', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE']

In [17]:
feature_df = pd.get_dummies(
    feature_df,
    columns=cat_cols,
    drop_first=True,
    dtype="int8"
)

In [18]:
print(feature_df.shape)

(307511, 220)

In [19]:
feature_df.select_dtypes(include="object").columns

Index([], dtype='object')

In [20]:
feature_df.dtypes.value_counts()

int8       116
float64     62
int64       42
Name: count, dtype: int64

In [22]:
feature_df["LOAN_TO_INCOME_RATIO"] = (
    feature_df["AMT_CREDIT"] /
    feature_df["AMT_INCOME_TOTAL"]
)

In [23]:
feature_df["ANNUITY_BURDEN"] = (
    feature_df["AMT_ANNUITY"] /
    feature_df["AMT_INCOME_TOTAL"]
)

In [21]:
feature_df["CREDIT_PER_CHILD"] = (
    feature_df["AMT_CREDIT"] /
    (feature_df["CNT_CHILDREN"] + 1)
)

In [24]:
feature_df["INCOME_PER_CREDIT"] = (
    feature_df["AMT_INCOME_TOTAL"] /
    feature_df["AMT_CREDIT"]
)

In [25]:
feature_df["CREDIT_GOODS_DIFF"] = (
    feature_df["AMT_CREDIT"] -
    feature_df["AMT_GOODS_PRICE"]
)

In [26]:
feature_df["CREDIT_GOODS_RATIO"] = (
    feature_df["AMT_CREDIT"] /
    feature_df["AMT_GOODS_PRICE"]
)

In [27]:
feature_df["INCOME_STABILITY"] = (
    feature_df["AMT_INCOME_TOTAL"] /
    (feature_df["YEARS_EMPLOYED"] + 1)
)

In [28]:
feature_df["FAMILY_BURDEN"] = (
    feature_df["CNT_CHILDREN"] /
    feature_df["CNT_FAM_MEMBERS"]
)

In [29]:
feature_df["EMPLOYMENT_PERCENT"] = (
    feature_df["YEARS_EMPLOYED"] /
    feature_df["AGE"]
)

In [30]:
feature_df["CREDIT_DENSITY"] = (
    feature_df["AMT_CREDIT"] /
    feature_df["AGE"]
)

In [31]:
new_features = [
    "LOAN_TO_INCOME_RATIO",
    "ANNUITY_BURDEN",
    "CREDIT_PER_CHILD",
    "INCOME_PER_CREDIT",
    "CREDIT_GOODS_DIFF",
    "CREDIT_GOODS_RATIO",
    "INCOME_STABILITY",
    "FAMILY_BURDEN",
    "EMPLOYMENT_PERCENT",
    "CREDIT_DENSITY"
]

feature_df[new_features].describe().T

,count,mean,std,min,25%,50%,75%,max
LOAN_TO_INCOME_RATIO,307511.0,3.957570,2.689728,0.004808,2.018667,3.265067,5.159880,8.473684e+01
ANNUITY_BURDEN,307511.0,0.180929,0.094573,0.000224,0.114782,0.162833,0.229067,1.875965e+00
CREDIT_PER_CHILD,307511.0,498366.640114,384327.607093,6750.000000,225000.000000,390960.000000,675000.000000,4.050000e+06
INCOME_PER_CREDIT,307511.0,0.399670,0.507924,0.011801,0.193803,0.306272,0.495376,2.080033e+02
CREDIT_GOODS_DIFF,307511.0,60709.705339,71034.266632,-765000.000000,0.000000,39204.000000,99792.000000,9.000000e+05
CREDIT_GOODS_RATIO,307511.0,1.122542,0.125542,0.150000,1.000000,1.118800,1.198000,6.000000e+00
INCOME_STABILITY,252137.0,41031.359907,79783.577609,791.788856,15230.769231,28521.126761,52941.176471,3.342857e+07
FAMILY_BURDEN,307511.0,0.125502,0.199578,0.000000,0.000000,0.000000,0.333333,9.500000e-01
EMPLOYMENT_PERCENT,252137.0,0.156859,0.133551,0.000000,0.056075,0.118712,0.219178,7.295691e-01
CREDIT_DENSITY,307511.0,14487.998310,10386.257005,659.824047,6858.778626,11968.085106,19438.701923,1.302251e+05

In [32]:
feature_df[new_features].isna().sum()

LOAN_TO_INCOME_RATIO        0
ANNUITY_BURDEN              0
CREDIT_PER_CHILD            0
INCOME_PER_CREDIT           0
CREDIT_GOODS_DIFF           0
CREDIT_GOODS_RATIO          0
INCOME_STABILITY        55374
FAMILY_BURDEN               0
EMPLOYMENT_PERCENT      55374
CREDIT_DENSITY              0
dtype: int64

In [33]:
import numpy as np

feature_df[new_features].isin([np.inf, -np.inf]).sum()

LOAN_TO_INCOME_RATIO    0
ANNUITY_BURDEN          0
CREDIT_PER_CHILD        0
INCOME_PER_CREDIT       0
CREDIT_GOODS_DIFF       0
CREDIT_GOODS_RATIO      0
INCOME_STABILITY        0
FAMILY_BURDEN           0
EMPLOYMENT_PERCENT      0
CREDIT_DENSITY          0
dtype: int64

In [34]:
feature_df["YEARS_EMPLOYED"].isna().sum()

55374

In [35]:
feature_df["INCOME_STABILITY"] = feature_df["INCOME_STABILITY"].fillna(0)
feature_df["EMPLOYMENT_PERCENT"] = feature_df["EMPLOYMENT_PERCENT"].fillna(0)

In [36]:
feature_df[
    ["INCOME_STABILITY", "EMPLOYMENT_PERCENT"]
].isna().sum()

INCOME_STABILITY      0
EMPLOYMENT_PERCENT    0
dtype: int64

In [37]:
print("Current Shape:", feature_df.shape)

Current Shape: (307511, 230)

In [38]:
corr_matrix = feature_df.corr().abs()

upper = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)

high_corr = [
    column for column in upper.columns
    if any(upper[column] > 0.95)
]

print("Highly Correlated Features:", len(high_corr))
high_corr

Highly Correlated Features: 29

['AMT_GOODS_PRICE',
 'REGION_RATING_CLIENT_W_CITY',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'LANDAREA_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAREA_MEDI',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'AGE',
 'YEARS_EMPLOYED',
 'NAME_INCOME_TYPE_Pensioner',
 'ORGANIZATION_TYPE_XNA',
 'LOAN_TO_INCOME_RATIO',
 'ANNUITY_BURDEN',
 'FAMILY_BURDEN',
 'EMPLOYMENT_PERCENT']

In [39]:
from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold(threshold=0.01)
selector.fit(feature_df.drop(columns="TARGET"))

low_variance = feature_df.drop(columns="TARGET").columns[
    ~selector.get_support()
]

print("Low Variance Features:", len(low_variance))
list(low_variance)

Low Variance Features: 106

['REGION_POPULATION_RELATIVE',
 'FLAG_MOBIL',
 'FLAG_CONT_MOBILE',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'ENTRANCES_AVG',
 'LANDAREA_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'LANDAREA_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAREA_MEDI',
 'TOTALAREA_MODE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'ANNUITY_INCOME_RATIO',
 'NAME_TYPE_SUITE_Group of people',
 'NAME_TYPE_SUITE_Other_A',
 'NAME_TYPE_SUITE_Other_B',
 'NAME_INCOME_TYPE_Maternity leave',
 'NAME_INCOME_TYPE_Student',
 'NAME_INCOME_TYPE_Unemployed',
 'NAME_FAMILY_STATUS_Unknown',
 'NAME_HOUSING_TYPE_Office apartment',
 'OCCUPATION_TYPE_HR staff',
 'OCCUPATION_TYPE_IT staff',
 'OCCUPATION_TYPE_Low-skill Laborers',
 'OCCUPATION_TYPE_Private service staff',
 'OCCUPATION_TYPE_Realty agents',
 'OCCUPATION_TYPE_Secretaries',
 'OCCUPATION_TYPE_Waiters/barmen staff',
 'ORGANIZATION_TYPE_Agriculture',
 'ORGANIZATION_TYPE_Bank',
 'ORGANIZATION_TYPE_Cleaning',
 'ORGANIZATION_TYPE_Culture',
 'ORGANIZATION_TYPE_Electricity',
 'ORGANIZATION_TYPE_Emergency',
 'ORGANIZATION_TYPE_Hotel',
 'ORGANIZATION_TYPE_Housing',
 'ORGANIZATION_TYPE_Industry: type 1',
 'ORGANIZATION_TYPE_Industry: type 10',
 'ORGANIZATION_TYPE_Industry: type 11',
 'ORGANIZATION_TYPE_Industry: type 12',
 'ORGANIZATION_TYPE_Industry: type 13',
 'ORGANIZATION_TYPE_Industry: type 2',
 'ORGANIZATION_TYPE_Industry: type 4',
 'ORGANIZATION_TYPE_Industry: type 5',
 'ORGANIZATION_TYPE_Industry: type 6',
 'ORGANIZATION_TYPE_Industry: type 7',
 'ORGANIZATION_TYPE_Industry: type 8',
 'ORGANIZATION_TYPE_Insurance',
 'ORGANIZATION_TYPE_Legal Services',
 'ORGANIZATION_TYPE_Military',
 'ORGANIZATION_TYPE_Mobile',
 'ORGANIZATION_TYPE_Police',
 'ORGANIZATION_TYPE_Postal',
 'ORGANIZATION_TYPE_Realtor',
 'ORGANIZATION_TYPE_Religion',
 'ORGANIZATION_TYPE_Restaurant',
 'ORGANIZATION_TYPE_Security Ministries',
 'ORGANIZATION_TYPE_Services',
 'ORGANIZATION_TYPE_Telecom',
 'ORGANIZATION_TYPE_Trade: type 1',
 'ORGANIZATION_TYPE_Trade: type 2',
 'ORGANIZATION_TYPE_Trade: type 4',
 'ORGANIZATION_TYPE_Trade: type 5',
 'ORGANIZATION_TYPE_Trade: type 6',
 'ORGANIZATION_TYPE_Transport: type 1',
 'ORGANIZATION_TYPE_Transport: type 2',
 'ORGANIZATION_TYPE_Transport: type 3',
 'ORGANIZATION_TYPE_University',
 'HOUSETYPE_MODE_specific housing',
 'HOUSETYPE_MODE_terraced house',
 'WALLSMATERIAL_MODE_Mixed',
 'WALLSMATERIAL_MODE_Monolithic',
 'WALLSMATERIAL_MODE_Others',
 'ANNUITY_BURDEN']

In [40]:
constant_cols = [
    col for col in feature_df.columns
    if feature_df[col].nunique() == 1
]

print("Constant Columns:", len(constant_cols))
constant_cols

Constant Columns: 0

[]

In [41]:
duplicate_cols = []

cols = feature_df.columns

for i in range(len(cols)):
    for j in range(i + 1, len(cols)):
        if feature_df[cols[i]].equals(feature_df[cols[j]]):
            duplicate_cols.append(cols[j])

print("Duplicate Columns:", len(duplicate_cols))
duplicate_cols

Duplicate Columns: 0

[]

In [42]:
print("Original Features :", feature_df.shape[1])
print("Highly Correlated :", len(high_corr))
print("Low Variance      :", len(low_variance))
print("Constant Columns  :", len(constant_cols))
print("Duplicate Columns :", len(duplicate_cols))

Original Features : 230
Highly Correlated : 29
Low Variance      : 106
Constant Columns  : 0
Duplicate Columns : 0

In [43]:
for col in high_corr:
    print(col)

AMT_GOODS_PRICE
REGION_RATING_CLIENT_W_CITY
APARTMENTS_MODE
BASEMENTAREA_MODE
YEARS_BEGINEXPLUATATION_MODE
ELEVATORS_MODE
ENTRANCES_MODE
FLOORSMAX_MODE
LANDAREA_MODE
LIVINGAREA_MODE
NONLIVINGAREA_MODE
APARTMENTS_MEDI
BASEMENTAREA_MEDI
YEARS_BEGINEXPLUATATION_MEDI
ELEVATORS_MEDI
ENTRANCES_MEDI
FLOORSMAX_MEDI
LANDAREA_MEDI
LIVINGAREA_MEDI
NONLIVINGAREA_MEDI
OBS_60_CNT_SOCIAL_CIRCLE
AGE
YEARS_EMPLOYED
NAME_INCOME_TYPE_Pensioner
ORGANIZATION_TYPE_XNA
LOAN_TO_INCOME_RATIO
ANNUITY_BURDEN
FAMILY_BURDEN
EMPLOYMENT_PERCENT

In [44]:
low_variance[:30]

Index(['REGION_POPULATION_RELATIVE', 'FLAG_MOBIL', 'FLAG_CONT_MOBILE',
       'APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG',
       'ENTRANCES_AVG', 'LANDAREA_AVG', 'LIVINGAREA_AVG', 'NONLIVINGAREA_AVG',
       'APARTMENTS_MODE', 'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE',
       'ELEVATORS_MODE', 'ENTRANCES_MODE', 'LANDAREA_MODE', 'LIVINGAREA_MODE',
       'NONLIVINGAREA_MODE', 'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI',
       'YEARS_BEGINEXPLUATATION_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI',
       'LANDAREA_MEDI', 'LIVINGAREA_MEDI', 'NONLIVINGAREA_MEDI',
       'TOTALAREA_MODE', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_4',
       'FLAG_DOCUMENT_7'],
      dtype='object')

In [45]:
drop_corr = [
    "APARTMENTS_MODE",
    "BASEMENTAREA_MODE",
    "YEARS_BEGINEXPLUATATION_MODE",
    "ELEVATORS_MODE",
    "ENTRANCES_MODE",
    "FLOORSMAX_MODE",
    "LANDAREA_MODE",
    "LIVINGAREA_MODE",
    "NONLIVINGAREA_MODE",

    "APARTMENTS_MEDI",
    "BASEMENTAREA_MEDI",
    "YEARS_BEGINEXPLUATATION_MEDI",
    "ELEVATORS_MEDI",
    "ENTRANCES_MEDI",
    "FLOORSMAX_MEDI",
    "LANDAREA_MEDI",
    "LIVINGAREA_MEDI",
    "NONLIVINGAREA_MEDI",

    "REGION_RATING_CLIENT_W_CITY",
    "OBS_60_CNT_SOCIAL_CIRCLE",

    "AGE",
    "YEARS_EMPLOYED",

    "ORGANIZATION_TYPE_XNA",

    "LOAN_TO_INCOME_RATIO",
    "ANNUITY_BURDEN",
    "FAMILY_BURDEN",
    "EMPLOYMENT_PERCENT"
]

In [46]:
feature_df = feature_df.drop(columns=drop_corr)

print("New Shape:", feature_df.shape)

New Shape: (307511, 203)

In [47]:
feature_df.to_csv(
    "../data/processed/HC_feature_engineered.csv",
    index=False
)

print("Feature engineered dataset saved successfully.")

Feature engineered dataset saved successfully.